services:
  autibot:
    build: .
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - HUGGINGFACE_TOKEN=${HUGGINGFACE_TOKEN}
      - ASTRA_DB_TOKEN=${ASTRA_DB_TOKEN}
      - ASTRA_DB_API_ENDPOINT=${ASTRA_DB_API_ENDPOINT}
    restart: unless-stopped